/** Shared column explanations; tables can override meanings that depend on context. */
const COLUMN_HELP: Record<string, string> = {
  rank: "Position in the current ranking. Equal results may share a rank.",
  player: "Open this player’s profile.",
  song: "Submitted song title and artist.",
  title: "The song title as provided in the submission.",
  artist: "Recording artist credited on the submitted song.",
  artists: "Number of distinct artists represented by these submissions.",
  submitter: "Player who submitted the song.",
  by: "Player who submitted the song.",
  submitters: "Number of distinct players who submitted these songs.",
  players: "Number of distinct players represented in this row.",
  league: "Music League competition containing these results.",
  leagues: "Number of distinct leagues containing these submissions.",
  round: "Round number and theme within its league.",
  "league / round": "League and round in which the song was submitted.",
  points: "Total points received in the selected scope.",
  pts: "Total points received by the song.",
  songs: "Number of song submissions included in this row.",
  submissions: "Number of submitted songs; repeated songs count as separate submissions.",
  subs: "Number of song submissions, including repeat submissions.",
  rounds: "Number of distinct rounds represented in the selected scope.",
  "entered rounds": "Number of distinct rounds the player entered in the selected scope.",
  "avg percentile": "Average round finishing percentile; higher values mean better finishes.",
  "avg round percentile": "Average round finishing percentile; higher values mean better finishes.",
  "round percentile": "Song's finishing percentile among the submissions in its round; higher is better.",
  wins: "Number of first-place round finishes, including ties.",
  "top 25%": "Proportion of entered rounds finished in the top quarter of players.",
  "top quartile": "Proportion of entered rounds finished in the top quarter of players.",
  "voters reached": "Share of eligible voters who awarded at least one point.",
  "adjusted support": "Support compared with an even share of available points. Above 1× is stronger; small samples are adjusted toward 1×.",
  "statistical surprise": "How far the score was above or below expectations, allowing for round size.",
  "positive reach": "How many voters gave the song points.",
  reach: "How many voters gave points, averaged across songs for a player.",
  share: "How much of the round’s points went to a song, averaged across songs for a player.",
  spread: "Positive means broader backing across voters. Negative means stronger backing from fewer voters.",
  chars: "Number of characters in the song title, including spaces and punctuation.",
  gap: "Difference between the highest and second-highest song shares of round points, in percentage points.",
  "top share": "Fraction of all eligible round points earned by the highest-scoring song.",
  "playlist quartile": "One of four roughly equal groups of songs in original playlist order, from earliest to latest.",
  "avg pts": "Average points per song.",
  "avg share": "Average share of the round’s points.",
  created: "Date and time this import was started.",
  "music league id": "Identifier of the league on Music League, used to match imported data.",
  status: "Current processing state of the import.",
  "progress / result": "Rows and chunks received while importing, song and vote totals on success, or an error on failure.",
  total: "Cumulative points through the selected round.",
  "this round": "Points earned in the selected round; a dash means the player did not enter.",
  "early avg": "Average points per displayed round in the first half, including missed rounds.",
  "late avg": "Average points per displayed round in the second half, including missed rounds.",
};

export function tableColumnHelp(label: string): string | undefined {
  return COLUMN_HELP[label.trim().replace(/\s+/g, " ").toLowerCase()];
}
