import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/layout/container";

export const metadata: Metadata = { title: "How the stats work", description: "Rankings, voting similarity and the numbers behind Music League results." };

const topics = [
  { id: "rankings", title: "Why do the rankings differ?", summary: "Points reward the total earned. Average round index compares performance across rounds of different sizes.", detail: "For each round, the player’s points are divided by the expected points for their submissions, then those round indexes are averaged. 1.0 means expected support. Adjusted rank always refers to this measure, even when the table is sorted by something else. The minimum rounds required is shown beside the results: roughly half the rounds for a small scope, easing to one third across all leagues. A dash means the player has not reached that threshold. Wins include ties; top quartile counts finishes in the top 25%." },
  { id: "song-measures", title: "What does each song measure tell me?", summary: "Songs starts with total points. Voters reached shows how many eligible voters gave the song at least one point.", detail: "Points per eligible voter includes zeroes; points per actual voter includes only voters who gave points. Round share is the song’s fraction of all eligible points in its round. Round percentile is its position within that round, with higher values meaning a better finish. Columns contains the additional measures. Choosing a sort also shows the relevant column." },
  { id: "adjusted-support", title: "How does adjusted support work?", summary: "It compares points with the round’s expected support and reduces extremes from small samples. The Home standout songs use it.", detail: "Raw support index = points ÷ expected points from eligible ballot budgets. Adjusted support is the empirical-Bayes estimate: the raw index is shrunk toward 1.0 using corpus-estimated variance, Var(SI) ≈ τ² + φ/E. It is an estimate, not an observed multiplier. When variance cannot be estimated, the raw index is used. Statistical surprise (support z) is (points − expected) ÷ √(φ × expected): a standardized surplus under the expected-support model. Neither measure is a judgment of musical quality." },
  { id: "voting-similarity", title: "Do these players vote alike?", summary: "Voting similarity runs from −100 to +100. Positive means agreement, zero means no linear agreement, and negative means opposing preferences.", detail: "Only songs both players could vote for are compared; both players’ own submissions are excluded. Votes, including inferred zeroes, are divided by the voter’s ballot budget and centered on their shared-song mean in each round. Cosine similarity compares the pooled deviations. Rounds where either shared ballot is flat do not contribute. This is not the percentage of songs both players liked. Shared-round and song-comparison counts describe the available sample. Mutual support is a separate measure: points exchanged divided by eligible ballot budgets." },
  { id: "zeroes", title: "Why are there votes worth zero?", summary: "An active voter could have chosen every eligible song they did not submit. Missing choices count as zero.", detail: "A ballot is active when it has at least one exported vote row, including an explicit zero. A scored submission was visible to voters or has exported votes. Self-votes are excluded. A player who submitted but did not vote creates no inferred zeroes and is marked as having missed the ballot. Imports keep the original rows; analytics adds eligible opportunities for calculation." },
  { id: "vote-details", title: "What are ballot blowout and crowd contrast?", summary: "They distinguish a voter’s unusually strong choices from scores that stand out among other voters.", detail: "Highest votes given sorts by points, with ballot blowout as its tiebreaker. Ballot blowout compares the score with an equal share of that voter’s ballot, divided again by the number of songs on the ballot scoring at least as much. Crowd contrast compares with points per eligible voter on that song, divided by the number of voters giving at least that score. The detail table can be searched and sorted independently." },
  { id: "facts", title: "How should I read the Facts page?", summary: "Repeated artists and songs are counts. Reach versus share describes whether support is broad or concentrated.", detail: "Spread is reach percentile minus round-share percentile, in percentage points; ties use midpoint percentiles. Positive means broader reach relative to point share, negative means more concentrated support. Song comparisons require at least five eligible voters; player comparisons require at least three songs and the participation threshold. Most repeated artists counts repeated submissions, not consecutive streaks. Playlist position and points reports correlation, not causation. Playlist quartiles contain nearly equal song counts, with leftover positions assigned to earlier groups." },
  { id: "graphs", title: "Which graph should I use?", summary: "League race follows standings. Voting similarity groups shared preferences. Support flow shows who gives points to whom.", detail: "Matrix compares every pair, including negative and zero similarity; an empty cell means no qualifying comparison. Player connections focuses on one person. Graphs describe voting behavior, not friendships or listening history. League race uses only rounds with exported votes; missed rounds add zero, multiple submissions are summed, and early/late averages split the displayed rounds in half (the middle round belongs to the early half). Selected round subsets restart totals at zero." },
  { id: "scope", title: "Which leagues am I looking at?", summary: "Pages open with all leagues. The league selector can choose the latest league, a single league, or a combination.", detail: "Scope is carried in navigation links and shared URLs. Public round filters are retired; graph progression can still show a subset of displayed rounds. A new league combination may need its results prepared before comparisons are available. Imports and refreshes can temporarily show an updating state. Exports do not include listening behavior, private intent or reliable voting-deadline context." },
  { id: "timing", title: "What does ballot position mean?", summary: "It shows how early a player voted compared with the other voters in that round. Lower is earlier.", detail: "The latest exported vote timestamp for each ballot is ranked within its round; ties use the middle position. Missing ballots do not enter the average. Timing does not establish whether someone voted before or after a deadline." },
];

export default function FaqPage() {
  return <Container className="py-6 sm:py-10">
    <div className="max-w-3xl">
      <h1 className="text-3xl font-semibold tracking-tight">How the stats work</h1>
      <nav aria-label="Metric topics" className="my-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-lime-300">
        <Link href="#rankings">Rankings</Link><Link href="#song-measures">Songs</Link><Link href="#voting-similarity">Voting similarity</Link><Link href="#zeroes">Zeroes</Link><Link href="#graphs">Graphs</Link>
      </nav>
      {topics.map(topic => <section key={topic.id} id={topic.id} className="scroll-mt-32 border-t border-white/10 py-6">
        <h2 className="text-lg font-semibold">{topic.title}</h2>
        <p className="mt-2 text-sm leading-6 text-zinc-300">{topic.summary}</p>
        <details className="mt-3 text-sm text-zinc-400"><summary className="cursor-pointer text-lime-300">Details</summary><p className="mt-3 leading-7">{topic.detail}</p></details>
      </section>)}
    </div>
  </Container>;
}
